# Codecov configuration for MoneyMaker
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  unit:
    paths:
      - shared/
      - services/
    carryforward: true

ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
  - "scripts/**/*"
